# -*- coding: utf-8 -*-
"""capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hRqrT-Jes_SlAXryK3ZIWUMGFIW6OMKx

## Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import chi2_contingency

"""**Thirza Elysia Chandra - CDCC325D6X1020 melakukan proses dari tahap menentukan pertanyaan bisnis, melakukan Data Wrangling hingga Exploratory Data Analysis**

## Pertanyaan Bisnis

1. Sejauh mana individu dalam dataset ini mematuhi alokasi budget persentase mereka dalam setiap kategori pengeluaran?
2. Kategori pengeluaran apa yang paling sering mengalami kondisi over budget dibandingkan alokasi budget persentase yang telah ditentukan pada setiap periode pengeluaran individu?
3. Berapa persentase individu yang memiliki tingkat tabungan sehat berdasarkan persentase savings terhadap income pada setiap periode pengeluaran?

# Data Wrangling

## Gathering Data
"""

# mengambil data dari file CSV lalu mengubahnya jadi tabel
df = pd.read_csv("urban_budget_allocation_dataset_dirty.csv", delimiter=",")

# menampilkan 5 baris pertama dari isi tabel
df.head()

"""**Insight :**

Dataset yang digunakan berasal dari Kaggle dengan topik Urban Allocation Budget. Dataset ini berisi data pendapatan, pengeluaran, dan tabungan masyarakat urban yang digunakan untuk menganalisis pola pengelolaan keuangan serta efektivitas alokasi anggaran pada berbagai kebutuhan sehari-hari. Dataset tersebut telah dimodifikasi oleh tim capstone agar sesuai dengan kebutuhan analisis. Penyesuaian dilakukan pada struktur, atribut, dan kualitas data sehingga lebih relevan dan mampu mendukung proses eksplorasi serta pengambilan insight secara optimal.

## Assesing Data
"""

# menampilkan jumlah baris dan kolom dari dataset
df.shape

# menampilkan nama kolom yang ada dalam dataset
df.columns

# memeriksa informasi dari isi dataset
df.info()

# memeriksa jumlah missing values dari dataset
df.isna().sum()

# Mengecek jumlah dan persentase missing values
missing_summary = pd.DataFrame({
    'Jumlah Missing': df.isna().sum(),
    'Persentase Missing': (
        df.isna().sum() / len(df) * 100
    ).round(2).astype(str) + '%'
})

# Tampilkan hanya kolom yang memiliki missing value
missing_summary = missing_summary[
    missing_summary['Jumlah Missing'] > 0
]

print(missing_summary)

# memeriksa duplikasi data dari dataset
print("Jumlah duplikasi: ",df.duplicated().sum())

# menampilkan ringkasan parameter statistik dataset
df.describe()

# mendeteksi dan menghitung jumlah outlier di tiap kolom numerik menggunakan metode IQR
cols = df.select_dtypes(include=['int64', 'float64']).columns

outliers = {}

total_data = len(df)

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    outlier_data = df[
        (df[col] < Q1 - 1.5 * IQR) |
        (df[col] > Q3 + 1.5 * IQR)
    ]

    outliers[col] = outlier_data

for col in outliers:
    jumlah_outlier = len(outliers[col])
    persen_outlier = (jumlah_outlier / total_data) * 100

    print(f"{col} : {jumlah_outlier} outlier ({persen_outlier:.2f}%)")

# menampilkan ringkasan parameter statistik dataset
df.describe()

"""**Insight :**

1. Dataset terdiri dari 13 kolom dan 1050 baris data terkait pengelolaan anggaran masyarakat urban.
2. Ditemukan missing value pada setiap kolom sehingga diperlukan proses data cleaning.
3. Terdapat ketidaksesuaian tipe data pada beberapa kolom yang perlu disesuaikan agar analisis lebih akurat.
4. Kolom untuk kategori budget (HousingBudget, TransportationBudget, FoodBudget, UtilitiesBudget, EntertainmentBudget, dan SavingsBudget) berbentuk persentase sehingga menggunakan tipe data float.
5. Dataset memiliki 46 data duplikat yang perlu dihapus untuk menjaga kualitas data.
6. Terdapat outlier pada beberapa kolom, namun tidak seluruh nilai outlier bersifat merusak karena sebagian masih merepresentasikan kondisi finansial yang realistis dalam dataset.

## Cleaning Data
"""

# menghapus duplikasi data pada tabel
df.drop_duplicates(inplace=True)

# membersihkan kolom Income dengan menghapus koma, teks USD, dan spasi, dan mengubah data menjadi tipe numerik
cols = [
    'Income',
]

for col in cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.replace('USD', '', regex=False)
        .str.strip()
    )

    df[col] = pd.to_numeric(df[col], errors='coerce')

# memeriksa duplikasi data dari dataset
print("Jumlah duplikasi: ",df.duplicated().sum())

# mengisi nilai kosong (NaN) dengan nilai median dari masing-masing kolom numerik
df = df.fillna(df.median(numeric_only=True))

# memeriksa jumlah missing values dari dataset setelah mengganti dengan nilai median
df.isna().sum()

# menampilkan ringkasan parameter statistik dataset
df.describe()

# menghapus duplikasi data pada tabel
df.drop_duplicates(inplace=True)

# memeriksa jumlah duplikasi dari tabel setelah menghapus duplikasi data
print("Jumlah duplikasi: ",df.duplicated().sum())

# menampilkan ringkasan parameter statistik dataset
df.describe()

# mengubah tipe data pada beberapa kolom menjadi integer
cols = [
    'Income',
    'HousingExpense',
    'TransportationExpense',
    'FoodExpense',
    'UtilitiesExpense',
    'EntertainmentExpense',
    'Savings'
]

df[cols] = df[cols].astype(int)

# menampilkan tipe data dari setiap kolom pada dataset
df.dtypes

# mendeteksi dan menghitung jumlah outlier di tiap kolom numerik menggunakan metode IQR
cols = df.select_dtypes(include=['int64', 'float64']).columns

outliers = {}

total_data = len(df)

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    outlier_data = df[
        (df[col] < Q1 - 1.5 * IQR) |
        (df[col] > Q3 + 1.5 * IQR)
    ]

    outliers[col] = outlier_data

for col in outliers:
    jumlah_outlier = len(outliers[col])
    persen_outlier = (jumlah_outlier / total_data) * 100

    print(f"{col} : {jumlah_outlier} outlier ({persen_outlier:.2f}%)")

# menghitung batas atas dan bawah kolom Income dan melakukan IQR capping
Q1 = df['Savings'].quantile(0.25)
Q3 = df['Savings'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower :", lower)
print("Upper :", upper)

df['Savings'] = df['Savings'].clip(lower, upper)

df['Savings'].describe()

# mengganti nilai negatif pada kolom Savings dan SavingsBudget dengan nilai median dari data yang valid
cols = ['Savings', 'SavingsBudget']

for col in cols:
    median_value = df.loc[df[col] >= 0, col].median()

    df.loc[df[col] < 0, col] = median_value

# menampilkan ringkasan parameter statistik dataset
df.describe()

# menghitung batas atas dan bawah kolom Income dan melakukan IQR capping
Q1 = df['Income'].quantile(0.25)
Q3 = df['Income'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower :", lower)
print("Upper :", upper)

df['Income'] = df['Income'].clip(lower, upper)

df['Income'].describe()

# menghitung batas atas dan bawah kolom HousingExpense dan melakukan IQR capping
Q1 = df['HousingExpense'].quantile(0.25)
Q3 = df['HousingExpense'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("HousingExpense :", lower)
print("HousingExpense :", upper)

df['HousingExpense'] = df['HousingExpense'].clip(lower, upper)

df['HousingExpense'].describe()

# menghitung batas atas dan bawah kolom Savings dan melakukan IQR capping
Q1 = df['Savings'].quantile(0.25)
Q3 = df['Savings'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower :", lower)
print("Upper :", upper)

df['Savings'] = df['Savings'].clip(lower, upper)

df['Savings'].describe()

# mendeteksi dan menghitung jumlah outlier di tiap kolom numerik menggunakan metode IQR setelah mengatasi outlier pada 3 kolom
cols = df.select_dtypes(include=['int64', 'float64']).columns

outliers = {}

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    outliers[col] = df[
        (df[col] < Q1 - 1.5 * IQR) |
        (df[col] > Q3 + 1.5 * IQR)
    ]

for col in outliers:
    print(col, ":", len(outliers[col]))

# menampilkan ringkasan parameter statistik dataset
df.describe()

# menyimpan dataset hasil cleaning ke file CSV tanpa menyertakan index
df.to_csv("urban_budget_allocation_dataset_clean.csv", index=False)

"""**Insight :**

1. Missing value ditangani dengan mengganti nilai yang kosong menggunakan median dari masing-masing kolom.
2. Data duplikat berhasil ditangani dengan menghapus seluruh data yang terdeteksi duplikat sehingga dataset menjadi lebih konsisten.
3. Beberapa kolom seperti Income, HousingExpense, TransportationExpense, FoodExpense, UtilitiesExpense, EntertainmentExpense, dan Savings diubah ke tipe data integer agar sesuai dengan representasi nilai numerik.
4. Nilai negatif pada kolom Savings dan SavingsBudget ditangani menggunakan median dari data valid.
5. Outlier pada kolom Income, HousingExpense, dan Savings ditangani menggunakan metode IQR Capping agar nilai ekstrem lebih terkendali.
6. Beberapa outlier tetap dipertahankan karena masih mencerminkan kondisi finansial yang realistis dan tidak terindikasi sebagai kesalahan data, sehingga variasi informasi dalam dataset tetap terjaga.

## Exploratory Data Analysis (EDA)

### Pertanyaan 1
"""

# membuat daftar kolom budget dan pengeluaran yang akan digunakan
budget_cols = [
    'HousingBudget',
    'TransportationBudget',
    'FoodBudget',
    'UtilitiesBudget',
    'EntertainmentBudget',
    'SavingsBudget'
]

expense_cols = [
    'HousingExpense',
    'TransportationExpense',
    'FoodExpense',
    'UtilitiesExpense',
    'EntertainmentExpense',
    'Savings'
]

# mengubah nilai budget dalam bentuk persentase menjadi nominal berdasarkan total Income
for col in budget_cols:
    df[col + 'Nominal'] = df['Income'] * df[col] / 100

# menghitung selisih antara pengeluaran aktual dan budget nominal pada setiap kategori
df['HousingDeviation'] = df['HousingExpense'] - df['HousingBudgetNominal']
df['TransportationDeviation'] = df['TransportationExpense'] - df['TransportationBudgetNominal']
df['FoodDeviation'] = df['FoodExpense'] - df['FoodBudgetNominal']
df['UtilitiesDeviation'] = df['UtilitiesExpense'] - df['UtilitiesBudgetNominal']
df['EntertainmentDeviation'] = df['EntertainmentExpense'] - df['EntertainmentBudgetNominal']
df['SavingsDeviation'] = df['Savings'] - df['SavingsBudgetNominal']

# menghitung total pengeluaran, total budget, dan rasio kepatuhan terhadap budget
df['TotalExpense'] = df[expense_cols].sum(axis=1)

df['TotalBudget'] = (
    df['HousingBudgetNominal'] +
    df['TransportationBudgetNominal'] +
    df['FoodBudgetNominal'] +
    df['UtilitiesBudgetNominal'] +
    df['EntertainmentBudgetNominal'] +
    df['SavingsBudgetNominal']
)

df['BudgetAdherenceRatio'] = df['TotalExpense'] / df['TotalBudget']

# mengelompokkan tingkat kepatuhan budget menggunakan variabel sementara
adherence_category = df['BudgetAdherenceRatio'].apply(
    lambda x: (
        "Under Budget" if x < 0.9
        else "On Track" if 0.9 <= x <= 1.1
        else "Over Budget"
    )
)

# menghitung jumlah
count_summary = adherence_category.value_counts()

# membuat ringkasan budget adherence
budget_summary = pd.DataFrame({
    'Jumlah': adherence_category.value_counts(),
    'Persentase': (
        adherence_category.value_counts(normalize=True) * 100
    ).round(2).astype(str) + '%'
})

print(budget_summary)

"""### Pertanyaan 2"""

# mengecek apakah pengeluaran pada setiap kategori melebihi budget yang telah ditentukan
df['HousingOverBudget'] = (
    df['HousingExpense'] > df['HousingBudgetNominal']
)

df['TransportationOverBudget'] = (
    df['TransportationExpense'] >
    df['TransportationBudgetNominal']
)

df['FoodOverBudget'] = (
    df['FoodExpense'] > df['FoodBudgetNominal']
)

df['UtilitiesOverBudget'] = (
    df['UtilitiesExpense'] >
    df['UtilitiesBudgetNominal']
)

df['EntertainmentOverBudget'] = (
    df['EntertainmentExpense'] >
    df['EntertainmentBudgetNominal']
)

df['SavingOverBudget'] = (
    df['Savings'] >
    df['SavingsBudgetNominal']
)

# menghitung jumlah kategori yang mengalami over budget
over_budget_counts = {
    'Housing': df['HousingOverBudget'].sum(),
    'Transportation': df['TransportationOverBudget'].sum(),
    'Food': df['FoodOverBudget'].sum(),
    'Utilities': df['UtilitiesOverBudget'].sum(),
    'Entertainment': df['EntertainmentOverBudget'].sum(),
    'Savings' : df['SavingOverBudget'].sum()
}

# mengubah data over budget menjadi DataFrame
result = pd.DataFrame({
    'Category': over_budget_counts.keys(),
    'OverBudgetCount': over_budget_counts.values()
})

# menghitung persentase over budget
result['PersentaseOverBudget'] = (
    result['OverBudgetCount'] / result['OverBudgetCount'].sum()
) * 100

# mengurutkan berdasarkan jumlah over budget tertinggi
result = result.sort_values(
    by='OverBudgetCount',
    ascending=False
)

result['PersentaseOverBudget'] = (
    result['PersentaseOverBudget']
    .round(2)
    .astype(str) + '%'
)

print(result)

"""### Pertanyaan 3"""

# menghitung persentase tabungan terhadap pendapatan
df['SavingsRate'] = df['Savings'] / df['Income']

# menentukan status tabungan berdasarkan persentase savings terhadap income
df['SavingsStatus'] = np.where(
    df['SavingsRate'] >= 0.2,
    'Healthy Saving',
    'Low Saving'
)

# menghitung jumlah data pada setiap kategori status tabungan
count_summary = df['SavingsStatus'].value_counts()

# menghitung persentase setiap kategori status tabungan
percentage_summary = (
    df['SavingsStatus']
    .value_counts(normalize=True) * 100
).round(2).astype(str) + '%'

# membuat dan menampilkan ringkasan jumlah serta persentase status tabungan
summary = pd.DataFrame({
    'Jumlah Individu': count_summary,
    'Persentase': percentage_summary
})

print(summary)

"""**Insight:**

1. Berdasarkan perhitungan tingkat kepatuhan terhadap anggaran, mayoritas data berada pada kategori under budget sebanyak 581 individu, diikuti kategori on track sebanyak 291 individu, dan over budget sebanyak 129 individu. Hasil ini menunjukkan bahwa sebagian besar individu masih mampu menjaga pengeluaran tetap berada di bawah anggaran yang ditetapkan.

2. Berdasarkan analisis pengeluaran yang melebihi anggaran, kategori HousingExpense menjadi pengeluaran yang paling sering melampaui budget dengan total 263 data. Posisi berikutnya ditempati Savings dan EntertainmentExpense dengan jumlah yang sama, yaitu 254 data, diikuti FoodExpense sebanyak 249 data, UtilitiesExpense sebanyak 248 data, dan TransportationExpense sebanyak 242 data. Hal ini menunjukkan bahwa kebutuhan tempat tinggal menjadi faktor pengeluaran yang paling sulit dikendalikan.

3. Berdasarkan analisis persentase tabungan terhadap pendapatan, mayoritas individu berada pada kategori Low Saving sebanyak 677 individu, sedangkan kategori Healthy Saving berjumlah 325 individu. Hal ini menunjukkan bahwa sebagian besar individu masih memiliki tingkat tabungan yang belum sehat dibandingkan pendapatannya.

**Richard Liestianto - CDCC325D6Y0418 melakukan proses dari tahap Feature Engineering, Visualization & Explanatory Analysis dan A/B Testing**

## Feature Engineering
"""

# menghitung sisa saldo dari pendapatan setelah dikurangi total pengeluaran
df['NetBalance'] = df['Income'] - df['TotalExpense']

# menentukan status keuangan berdasarkan sisa saldo
df['FinancialStatus'] = df['NetBalance'].apply(
    lambda x: 'Surplus' if x > 0 else 'Deficit'
)

# membuat ringkasan jumlah dan persentase untuk setiap kategori status keuangan
status_summary = pd.DataFrame({
    'Jumlah Individu': df['FinancialStatus'].value_counts(),
    'Persentase': (
        df['FinancialStatus']
        .value_counts(normalize=True) * 100
    ).round(2)
})

# mengelompokkan tingkat kondisi keuangan berdasarkan nilai saldo
df['FinancialLevel'] = pd.cut(
    df['NetBalance'],
    bins=[-float('inf'), 0, 1000, float('inf')],
    labels=['Unhealthy', 'At Risk', 'Healthy']
)

# membuat visualisasi persentase status tabungan individu dalam bentuk diagram batang
level_summary = pd.DataFrame({
    'Jumlah Individu': df['FinancialLevel'].value_counts(),
    'Persentase': (
        df['FinancialLevel']
        .value_counts(normalize=True) * 100
    ).round(2)
})

# menghitung jumlah kategori pengeluaran yang mengalami over budget pada setiap data
df['OverBudgetCount'] = (
    df[
        [
            'HousingOverBudget',
            'TransportationOverBudget',
            'FoodOverBudget',
            'UtilitiesOverBudget',
            'EntertainmentOverBudget'
        ]
    ]
    .sum(axis=1)
)

# menghapus kolom sementara yang sudah tidak digunakan
temporary_columns = [
    'HousingBudgetNominal',
    'TransportationBudgetNominal',
    'FoodBudgetNominal',
    'UtilitiesBudgetNominal',
    'EntertainmentBudgetNominal',
    'SavingsBudgetNominal'
]

df.drop(columns=temporary_columns, inplace=True)

# memilih kolom yang akan digunakan lalu menampilkan 5 data pertama
selected_columns = [

    # Original Features
    'Income',
    'HousingExpense',
    'TransportationExpense',
    'FoodExpense',
    'UtilitiesExpense',
    'EntertainmentExpense',
    'Savings',

    # Engineered Features
    'TotalExpense',
    'NetBalance',
    'BudgetAdherenceRatio',
    'OverBudgetCount',
    'FinancialStatus',
    'FinancialLevel',
    'SavingsRate',
    'SavingsStatus'
]

print(df[selected_columns].head())

# memilih kolom akhir yang akan digunakan pada dataset
final_columns = [

    # Original Columns
    'Income',
    'HousingExpense',
    'TransportationExpense',
    'FoodExpense',
    'UtilitiesExpense',
    'EntertainmentExpense',
    'Savings',

    # Engineered Features
    'TotalExpense',
    'NetBalance',

    # Original Columns
    'HousingBudget',
    'TransportationBudget',
    'FoodBudget',
    'UtilitiesBudget',
    'EntertainmentBudget',
    'SavingsBudget',

    # Engineered Features
    'BudgetAdherenceRatio',
    'OverBudgetCount',
    'FinancialStatus',
    'FinancialLevel',
    'SavingsRate',
    'SavingsStatus'
]

df = df[final_columns]

# menampilkan jumlah dan nama seluruh kolom pada dataset
print("\nTotal Columns:", len(df.columns))

print("\nAll Columns:")
for col in df.columns:
    print("-", col)

df.dtypes

# menyimpan dataset akhir ke file CSV tanpa menyertakan index
df.to_csv("urban_budget_allocation_dataset.csv", index=False)

# menyimpan dataset ke file JSON
df.to_json("urban_budget_allocation_dataset.json", orient="records", indent=4)

"""**Insight :**
1. Menambahkan fitur TotalExpense untuk merepresentasikan total keseluruhan pengeluaran pengguna termasuk tabungan (savings), serta fitur NetBalance yang dihitung dari selisih antara pendapatan dan total pengeluaran (Income - TotalExpense) guna menggambarkan kondisi saldo keuangan pengguna.
2. Mengembangkan fitur kategorisasi finansial seperti FinancialStatus (Surplus dan Deficit) serta FinancialLevel (Unhealthy, At Risk, dan Healthy) berdasarkan nilai NetBalance untuk membantu segmentasi kondisi kesehatan finansial pengguna.
3. Menambahkan fitur analisis pengelolaan keuangan berupa BudgetAdherenceRatio untuk mengukur kepatuhan terhadap anggaran, SavingsRate untuk menghitung persentase tabungan terhadap pendapatan, SavingsStatus untuk mengelompokkan kebiasaan menabung pengguna, serta OverBudgetCount untuk menghitung jumlah kategori pengeluaran yang melebihi budget.
4. Memanfaatkan fitur BudgetAdherenceRatio, FinancialStatus, FinancialLevel, SavingsStatus, dan OverBudgetCount dalam proses visualisasi data guna menghasilkan insight finansial yang lebih informatif, interaktif, dan mudah dipahami pengguna.

## Visualization & Explanatory Analysis
"""

# pertanyaan 1
# visualisasi distribusi kepatuhan budget menentukan nilai tertinggi menentukan nilai tertinggi
max_value = budget_summary['Jumlah'].max()

plt.figure(figsize=(6,5))

plt.bar(
    budget_summary.index,
    budget_summary['Jumlah'],
)

plt.title("Budget Adherence Distribution")
plt.xlabel("Category")
plt.ylabel("Number of Individuals")

plt.ylim(0, budget_summary['Jumlah'].max() + 50)

plt.xticks(rotation=0)

plt.show()

# pertanyaan 2
# membuat diagram batang untuk menampilkan kategori dengan frekuensi over budget tertinggi
max_value = result['OverBudgetCount'].max()

colors = [
    'crimson' if value == max_value else 'steelblue'
    for value in result['OverBudgetCount']
]

plt.figure(figsize=(8,5))

plt.bar(
    result['Category'],
    result['OverBudgetCount'],
    color=colors
)

plt.title("Most Frequent Over Budget Categories")
plt.xlabel("Expense Category")
plt.ylabel("Frequency")

plt.xticks(rotation=0)

plt.show()

# pertanyaan 3
# membuat visualisasi persentase status tabungan individu dalam bentuk diagram batang
max_value = summary['Jumlah Individu'].max()

colors = [
    'crimson' if value == max_value else 'steelblue'
    for value in summary['Jumlah Individu']
]

plt.figure(figsize=(6,5))

plt.bar(
    summary.index,
    summary['Jumlah Individu'],
    color=colors
)

for i, value in enumerate(summary['Jumlah Individu']):
    plt.text(
        i,
        value + 5,
        summary['Persentase'].iloc[i],
        ha='center'
    )

plt.title("Savings Status Distribution")
plt.xlabel("Savings Status")
plt.ylabel("Number of Individuals")

plt.ylim(0, summary['Jumlah Individu'].max() + 50)

plt.show()

# membuat visualisasi distribusi tingkat kondisi keuangan individu dalam bentuk diagram pie
max_value = level_summary['Persentase'].max()

colors = [
    'steelblue',
    'slategray',
    'cadetblue'
]

# 1. Sesuaikan figsize menjadi (5, 3.5) seperti di Streamlit
fig, ax = plt.subplots(figsize=(5, 3.5))

# 2. Atur posisi lingkaran agar membesar ke bawah dan menyisakan ruang untuk judul
ax.set_position([0.1, 0.15, 0.8, 0.75])

# 3. Hilangkan argumen `labels=` agar teks tidak menempel di lingkaran
wedges, texts, autotexts = ax.pie(
    level_summary['Persentase'],
    autopct='%1.2f%%',
    colors=colors,
    wedgeprops={'width': 0.7}
)

# 4. Tambahkan padding pada judul
ax.set_title('Distribution of Individual Financial Levels', pad=5)

# 5. Tambahkan legenda di bawah lingkaran (sama persis dengan format Streamlit)
ax.legend(
    wedges,
    level_summary.index,
    loc="upper center",
    bbox_to_anchor=(0.5, -0.02),
    ncol=3,
    frameon=False
)

plt.show()

# Membuat visualisasi distribusi status finansial individu dalam bentuk diagram pie
max_val_status = status_summary['Persentase'].max()

# Warna dinamis: steelblue untuk nilai tertinggi, slategray untuk sisanya
colors_status = ['steelblue' if val == max_val_status else 'slategray' for val in status_summary['Persentase']]

# 1. Menyesuaikan figsize menjadi (5, 3.5)
fig, ax = plt.subplots(figsize=(5, 3.5))

# 2. Mengatur posisi area lingkaran agar membesar ke bawah
ax.set_position([0.1, 0.15, 0.8, 0.75])

# 3. Membuat pie chart tanpa label teks di pinggiran (labels dihapus)
wedges, texts, autotexts = ax.pie(
    status_summary['Persentase'],
    autopct='%1.2f%%',
    colors=colors_status,
    wedgeprops={'width': 0.7} # Ketebalan donut chart
)

# 4. Menambahkan judul dengan padding
ax.set_title('Distribution of Financial Status', pad=5)

# 5. Menambahkan legenda di bagian bawah dengan 2 kolom (ncol=2)
ax.legend(
    wedges,
    status_summary.index,
    loc="upper center",
    bbox_to_anchor=(0.5, -0.02),
    ncol=2,
    frameon=False
)

plt.show()

"""**Insight :**

1. Mayoritas Individu Patuh Terhadap Anggaran (Budget Adherence)

    Sebagian besar populasi memiliki kontrol pengeluaran yang baik, didominasi oleh kelompok Under Budget dan kelompok On Track yang disiplin, sementara kelompok yang melebihi anggaran (Over Budget) berada di jumlah paling minim.

2. Kategori Tertentu Menjadi Pemicu Utama Kebocoran Dana (Most Frequent Over Budget)
    
    Kategori pengeluaran spesifik yang berwarna merah (crimson) berhasil diidentifikasi sebagai sektor yang paling sering melampaui batas anggaran, menjadikannya prioritas utama untuk penyesuaian strategi atau fitur peringatan (alerting).

3. Mayoritas Individu Memiliki Kebiasaan Menabung yang Rendah (Savings Status)
    
    Terjadi ketimpangan besar dalam perilaku menabung, di mana sebanyak 67.56% individu masuk dalam kategori Low Saving dan hanya 32.44% yang berhasil menyisihkan tabungan secara ideal (Healthy Saving).

4. Kesehatan Finansial Didominasi Kategori Aman (Financial Levels)
    
    Sebanyak 70.26% individu berhasil mencapai tingkat keuangan yang Healthy, namun terdapat hampir 30% populasi gabungan Unhealthy dan At Risk yang diduga terdampak oleh rendahnya alokasi tabungan mereka.

5. Kondisi Saldo Keseluruhan Lebih Banyak Mengalami Surplus (Financial Status)
    
    Sebagian besar pengguna berhasil mempertahankan status finansial positif (Surplus) di mana pendapatan lebih besar dari total pengeluaran, sedangkan sebagian kecil sisanya berada dalam kondisi Deficit yang membutuhkan evaluasi anggaran.

## A/B Testing
"""

# Definisikan Hipotesis
print("H0: Tidak ada perbedaan rata-rata pengeluaran hiburan antara kelompok Surplus dan Deficit.")
print("H1: Terdapat perbedaan rata-rata pengeluaran hiburan yang signifikan antara kelompok Surplus dan Deficit.\n")

# Pisahkan data menjadi dua kelompok
group_surplus = df[df['FinancialStatus'] == 'Surplus']['EntertainmentExpense']
group_deficit = df[df['FinancialStatus'] == 'Deficit']['EntertainmentExpense']

# Lakukan T-Test
t_stat, p_value = stats.ttest_ind(group_surplus, group_deficit, equal_var=False, nan_policy='omit')

# Tampilkan Hasil Statistik
print(f"Rata-rata Entertainment Surplus : {group_surplus.mean():.2f}")
print(f"Rata-rata Entertainment Deficit : {group_deficit.mean():.2f}")
print("-" * 30)
print(f"T-Statistic : {t_stat:.4f}")
print(f"P-Value     : {p_value:.4f}")

# Buat Kesimpulan Otomatis (Tingkat Kepercayaan 95%)
alpha = 0.05
print("\n--- KESIMPULAN ---")
if p_value < alpha:
    print("Kita Menolak H0.")
    print("Insight: Terdapat perbedaan yang SIGNIFIKAN secara statistik pada pengeluaran hiburan antara individu Surplus dan Deficit.")
else:
    print("Kita Gagal Menolak H0.")
    print("Insight: TIDAK ADA perbedaan yang signifikan pada pengeluaran hiburan antara individu Surplus dan Deficit.")

# Filter data khusus untuk Surplus dan Deficit
df_ab1 = df[df['FinancialStatus'].isin(['Surplus', 'Deficit'])]

plt.figure(figsize=(8, 6))

# Membuat Barplot
ax_ab1 = sns.barplot(
    x='FinancialStatus',
    y='EntertainmentExpense',
    data=df_ab1,
    palette={'Surplus': '#3a86c8', 'Deficit': '#e63946'},
    capsize=0.1,
    errorbar='ci'
)

# Kustomisasi Judul dan Label (Translasi ke Bahasa Inggris)
plt.title("Average Entertainment Expense\nSurplus vs Deficit", pad=15, fontweight='bold', fontsize=14)
plt.xlabel("Financial Status", fontweight='bold', fontsize=12)
plt.ylabel("Entertainment Expense", fontweight='bold', fontsize=12)

# --- SOLUSI RUANG KOSONG ---
# Mengambil batas atas tertinggi lalu menambah area kosong 40% di atasnya
current_max_y = ax_ab1.get_ylim()[1]
ax_ab1.set_ylim(0, current_max_y * 1.4)

# Menambahkan Kotak Anotasi Kesimpulan Statistik (Translasi ke Bahasa Inggris)
# Catatan: Variabel t_stat dan p_value disesuaikan dengan variabel di IPYNB kamu
sig_text1 = f"T-Stat: {t_stat:.2f} | P-Value: {p_value:.4f}\n({'Significant' if p_value < 0.05 else 'Not Significant'})"

# Menggunakan transform=ax_ab1.transAxes agar posisi teks relatif terhadap kanvas
plt.text(
    0.5, 0.95,
    sig_text1,
    transform=ax_ab1.transAxes,
    ha='center', va='top', fontsize=11, color='black',
    bbox=dict(facecolor='#f8f9fa', edgecolor='gray', boxstyle='round,pad=0.5')
)

plt.show()

# Definisikan Hipotesis
print("H0: Tidak ada hubungan yang signifikan antara Status Tabungan dan Jumlah Kategori Kebocoran (Over Budget).")
print("H1: Terdapat hubungan yang signifikan antara Status Tabungan dan Jumlah Kategori Kebocoran.\n")

# Mengelompokkan OverBudgetCount menjadi kategori agar cocok untuk Chi-Square
def kelompokkan_kebocoran(x):
    if x == 0:
        return '0 Leaks'
    elif x <= 2:
        return '1-2 Leaks'
    else:
        return '>2 Leaks'

df['KebocoranCategory'] = df['OverBudgetCount'].apply(kelompokkan_kebocoran)

# Memastikan kita hanya mengambil data yang relevan
df_filtered = df[df['SavingsStatus'].isin(['Healthy Saving', 'Low Saving'])]

# Membuat Tabel Kontingensi (Cross Tabulation)
contingency_table = pd.crosstab(df_filtered['SavingsStatus'], df_filtered['KebocoranCategory'])

print("--- Tabel Kontingensi (Jumlah Individu) ---")
print(contingency_table)
print("\n" + "-" * 40)

# Melakukan Uji Chi-Square
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

# Tampilkan Hasil Statistik
print(f"Chi-Square Statistic : {chi2_stat:.4f}")
print(f"P-Value              : {p_value:.4f}")
print(f"Degrees of Freedom   : {dof}")

# Buat Kesimpulan Otomatis (Tingkat Kepercayaan 95%)
alpha = 0.05
print("\n--- KESIMPULAN ---")
if p_value < alpha:
    print("Kita Menolak H0.")
    print("Insight: Terdapat hubungan yang SIGNIFIKAN secara statistik antara status tabungan seseorang dengan seberapa sering anggaran mereka jebol.")
else:
    print("Kita Gagal Menolak H0.")
    print("Insight: TIDAK ADA hubungan yang signifikan antara status tabungan dan jumlah kebocoran anggaran.")

plt.figure(figsize=(9, 6))

# Membuat Grouped Bar Chart menggunakan countplot
# Warna: Hijau (Aman/0), Kuning (Peringatan/1-2), Merah (Bahaya/>2)
ax_ab3 = sns.countplot(
    data=df_filtered,
    x='SavingsStatus',
    hue='KebocoranCategory',
    hue_order=['0 Leaks', '1-2 Leaks', '>2 Leaks'],
    palette=['#2a9d8f', '#e9c46a', '#e76f51']
)

# Menambahkan label angka pasti di atas setiap batang
for container in ax_ab3.containers:
    ax_ab3.bar_label(container, padding=3, fontweight='bold', color='#333333')

# Kustomisasi Judul, Label, dan Legenda
plt.title("Category Leaks based on Savings Status\n(Chi-Square)", pad=20, fontweight='bold', fontsize=14)
plt.xlabel("Savings Status", fontweight='bold', fontsize=12)
plt.ylabel("Number of Individuals", fontweight='bold', fontsize=12)
plt.legend(title="Leak Level", title_fontsize='11', fontsize='10')

# Mencegah sumbu Y memunculkan angka minus
plt.ylim(bottom=0)

# Menambahkan Kotak Anotasi Statistik
significance_text = f"Chi-Square Stat: {chi2_stat:.2f} | P-Value: {p_value:.4f}\n(Significant)"

plt.text(
    0.5, 0.95,
    significance_text,
    transform=ax_ab3.transAxes,
    ha='center', va='top', fontsize=11, color='black',
    bbox=dict(facecolor='#f8f9fa', edgecolor='gray', boxstyle='round,pad=0.5')
)

plt.tight_layout()
plt.show()